# Generated by Django 4.1.3 on 2022-12-30 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Category',
            new_name='category',
        ),
    ]
